package com.smarthotel.payment.wallet.entity;

public enum WalletTransactionType {
    PLATFORM_COMMISSION,
    HOTEL_REVENUE_PENDING,
    HOTEL_REVENUE_RELEASED,
    WALLET_TOP_UP,
    WITHDRAWAL_HOLD,
    WITHDRAWAL_RELEASED,
    WITHDRAWAL_PAID,
    REFUND_DEBIT,
    MANUAL_ADJUSTMENT,
    CUSTOMER_REFUND_CREDIT,
    CUSTOMER_PAYMENT_DEBIT,
    CASH_REVENUE_RECORDED,
    HOTEL_COMMISSION_DEBIT,
    HOTEL_COMMISSION_DEBT_ACCRUED,
    HOTEL_COMMISSION_DEBT_SETTLED
}
