spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/payment_db}
    username: ${DB_USERNAME:payment_user}
    password: ${DB_PASSWORD:payment_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

clients:
  booking:
    base-url: ${BOOKING_SERVICE_URL:http://localhost:8083}
