FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre-alpine
RUN addgroup -S -g 10001 app && adduser -S -u 10001 -G app app
WORKDIR /app
COPY --from=build --chown=app:app /app/target/*.jar app.jar
RUN chmod 0444 /app/app.jar
USER app:app
EXPOSE 8087
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
