package com.smarthotel.booking.complaint.entity;

public enum ComplaintResolutionType {
    EXPLANATION_NO_FURTHER_ACTION,
    HOTEL_SUPPORT_REQUIRED,
    FULL_REFUND_ACCEPTED,
    PARTIAL_REFUND_ACCEPTED,
    REJECTED_INSUFFICIENT_EVIDENCE,
    REJECTED_CUSTOMER_AT_FAULT,
    HOTEL_ACKNOWLEDGED_FAULT,
    MUTUAL_AGREEMENT,
    ESCALATED_HOTEL_VIOLATION
}
