package com.smarthotel.booking.complaint.entity;

public enum ComplaintEventType {
    SUBMITTED,
    CUSTOMER_EVIDENCE_ADDED,
    HOTEL_RESPONSE_ADDED,
    ESCALATED_TO_SYSTEM,
    HOTEL_ACTION_REQUIRED,
    HOTEL_ACTION_COMPLETED,
    HOTEL_RESOLVED,
    SYSTEM_CONFIRMED,
    ADMIN_NOTE_ADDED,
    STATUS_CHANGED,
    RESOLUTION_RECORDED,
    REFUND_LINKED,
    CANCELLED
}
