package com.smarthotel.notification.notification.entity;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    BOOKING_CANCELLED,
    BOOKING_CHECKED_IN,
    BOOKING_CHECKED_OUT,
    ROOM_CLEANING,
    ROOM_READY,
    REVIEW_CREATED,
    PARTNER_REQUEST,
    HOTEL_SUBMITTED,
    WITHDRAWAL_REQUEST,
    WITHDRAWAL_STATUS,
    SYSTEM
}
